spring.application.name=favorite-movies

spring.datasource.url=jdbc:postgresql://localhost:5432/favorite_movies
spring.datasource.username=postgres
spring.datasource.password=admin123


#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration

spring.security.user.name=admin
spring.security.user.password=admin123


